apiVersion: "etcd.coreos.com/v1beta1"
kind: "Cluster"
metadata:
  name: "example-etcd-cluster"
spec:
  size: 3
  version: "3.1.2"
  TLS:
    static:
      member:
        peerSecret: etcd-operator-peer
        clientSecret: etcd-operator-client
